mojicollage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('result/', views.result, name='result'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mojicollage.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mojicollage/models.py
from django.db import models

# Create your models here.

mojicollage/forms.py
from django import forms

from mojicollage.widgets import RangeInput

class createInfo(forms.Form):
    tgtImg = forms.ImageField(label='画像を選択')
    myName = forms.CharField(label='自分の名前（呼ばれかた）（任意）', required=False, max_length=20)
    myAge = forms.IntegerField(label='自分の年齢（任意）', required=False)
    tgtName = forms.CharField(label='女の子の名前（任意）', required=False, max_length=20)
    tgtAge = forms.IntegerField(label='女の子の年齢（任意）', required=False)
    tgtSeikaku = forms.IntegerField(label='女の子の性格', min_value=1, max_value=5, widget=RangeInput)
    tgtKeigo = forms.ChoiceField(
        label='女の子の話し方',
        choices = (
            ('0', 'ため口'),
            ('1', '敬語')
        ),
        widget=forms.widgets.RadioSelect
    )
    finish = forms.ChoiceField(
        label='射精',
        choices = (
            ('0', 'おまかせ'),
            ('1', '我慢する'),
            ('2', '限界。。')
        ),
        widget=forms.widgets.RadioSelect
    )

mojicollage/views.py
from django.shortcuts import render
from .forms import createInfo
from django.core.files.storage import default_storage
from .collage import createCollage
from .FileUtil import *

def home(request):
    """ホーム画面"""
    initial_dict = {
        'tgtSeikaku':'3',
        'tgtKeigo':'0',
        'finish':'1',
    }
    form = createInfo(initial=initial_dict)
    return render(request, 'mojicollage/home.html', {'form': form})

def result(request):
    """結果画面"""
    form = createInfo(request.POST, request.FILES)
    if form.is_valid() and form.errors.__len__()==0:
        img = form.files['tgtImg']
        # キー発行
        imgKey = createKey(10)
        # 保存用フォルダに保存（キー＋'_'＋原本ファイル名）
        saveFileName = default_storage.save(imgKey+'_' + img.name, img)
        # 作業用フォルダにコピーを作成
        tmpFileName = saveTmp(saveFileName, imgKey)
        
        createCollage(tmpFileName, imgKey)

        tmpImgUrl = default_storage.url(tmpFileName)
        return render(request, 'mojicollage/result.html', {'imgUrl': tmpImgUrl})
    return render(request, 'mojicollage/home.html', {'form': form})

mojicollage/templates/mojicollage/base.html
{% load static %}

<html>
    <head>
        <title>MojiM</title>
        <link href="//db.onlinewebfonts.com/c/02b58c959a917f917b442d2f948b7d09?family=Luthier+It" rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/mojicollage.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    </head>
    <body class="page-body">
        <div class="page-header">
            <h1><a href="{% url 'home' %}">MojiM</a></h1>
        </div>
        {% block content %}
        {% endblock %}
        <script src="{% static 'js/mojicollage.js' %}"></script>
    </body>
</html>

mojicollage/templates/mojicollage/home.html
{% extends 'mojicollage/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="content">
    <br>
    <form enctype="multipart/form-data" action="{% url 'result' %}" method="POST">{% csrf_token %}
        {% for field in form %}
            {% if field.label == "画像を選択" %}
                <label for="id_tgtImg" class="filelabel">{{ field.label }}</label>
                {{ form.tgtImg | add_class:'fileinput'}}
                <p><canvas id="preview" style="max-height:150px;"></canvas></p>
                {{ field.errors }}
            {% elif field.label == "女の子の性格" %}
                {{ field.label }}:
                <span id="seikaku-value"></span></label> {{ field }}
                {{ field.errors }}
                <br><br>
            {% elif field.label == "女の子の話し方" or field.label == "射精" %}
                {{ field.label }}:
                {% for choice in field %}
                    <label>{{ choice.tag }}{{ choice.choice_label }}</label>
　　         　 {% endfor %}
                {{ field.errors }}
                <br><br>
            {% else %}
                {{ field.label }}:
                {{ field }}
                {{ field.errors }}
                <br><br>
            {% endif %}
        {% endfor %}
        <button type="submit" class="Button-style" disabled=true>つくる</button>
    </form>
    <br><br>
</div>
{% endblock %}

mojicollage/templates/mojicollage/result.html
{% extends 'mojicollage/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="content">
    <br>
    <img src="{{ imgUrl }}" class="result-Img-1" id="id_imgUrl">
    <br><br>
    <button class="Button-style-result" onclick="history.back()">←前へ</button>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <button class="Button-style-result" onclick="window.location.reload()">更新→</button>
    <br><br>
    <button class="Button-style-GoToHome" onclick="location.href='{% url 'home' %}'">ホームへ戻る</button>
</div>
{% endblock %}